/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_Cliente = new javax.swing.JMenuItem();
        item_Fornecedor = new javax.swing.JMenuItem();
        item_Produto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        item_Compra = new javax.swing.JMenuItem();
        item_Venda = new javax.swing.JMenu();
        item_Vender = new javax.swing.JMenuItem();
        item_Sair = new javax.swing.JMenu();
        item_sai = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Sitema de Contabilidade");

        jMenu1.setText("Cadastro");

        item_Cliente.setText("Cliente");
        item_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(item_Cliente);

        item_Fornecedor.setText("Fornecedor");
        item_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_FornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(item_Fornecedor);

        item_Produto.setText("Produto");
        item_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(item_Produto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compra");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        item_Compra.setText("Comprar");
        item_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_CompraActionPerformed(evt);
            }
        });
        jMenu2.add(item_Compra);

        jMenuBar1.add(jMenu2);

        item_Venda.setText("Venda");

        item_Vender.setText("Vender");
        item_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_VenderActionPerformed(evt);
            }
        });
        item_Venda.add(item_Vender);

        jMenuBar1.add(item_Venda);

        item_Sair.setText("Sair");

        item_sai.setText("Sair");
        item_sai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_saiActionPerformed(evt);
            }
        });
        item_Sair.add(item_sai);

        jMenuBar1.add(item_Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_FornecedorActionPerformed
        CadastroFornecedor cadFornecedor = new CadastroFornecedor();
        cadFornecedor.setVisible(true);    }//GEN-LAST:event_item_FornecedorActionPerformed

    private void item_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_CompraActionPerformed
        Compra compra = new Compra();
        compra.setVisible(true);
    }//GEN-LAST:event_item_CompraActionPerformed

    private void item_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ClienteActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        cadCliente.setVisible(true);    }//GEN-LAST:event_item_ClienteActionPerformed

    private void item_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ProdutoActionPerformed
        CadastroProduto cadProduto = new CadastroProduto();
        cadProduto.setVisible(true);    }//GEN-LAST:event_item_ProdutoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void item_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_VenderActionPerformed
        Venda venda = new Venda();
        venda.setVisible(true);
    }//GEN-LAST:event_item_VenderActionPerformed

    private void item_saiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_saiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_item_saiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_Cliente;
    private javax.swing.JMenuItem item_Compra;
    private javax.swing.JMenuItem item_Fornecedor;
    private javax.swing.JMenuItem item_Produto;
    private javax.swing.JMenu item_Sair;
    private javax.swing.JMenu item_Venda;
    private javax.swing.JMenuItem item_Vender;
    private javax.swing.JMenuItem item_sai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
