/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.CompraDAO;
import DAO.VendaDAO;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import util.ICMS;

/**
 *
 * @author pedro
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioCompra
     */
    public Relatorio() {
        initComponents();
        preencheTabela();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Relatorio = new javax.swing.JTable();
        JblCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Relatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "UF", "Fornecedor", "UF", "Preço - Venda", "ICMS", "Preço - Compra", "Pagamento"
            }
        ));
        jScrollPane1.setViewportView(tbl_Relatorio);

        JblCadastro.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        JblCadastro.setText("Relatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JblCadastro)
                .addGap(360, 360, 360))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(JblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheTabela() {
    /*DefaultTableModel modelo = (DefaultTableModel) tbl_Relatorio.getModel();
    modelo.setRowCount(0); // limpa a tabela antes de preencher

    VendaDAO vendaDAO = new VendaDAO();
    CompraDAO compraDAO = new CompraDAO();
    
    List<Venda> listaVendas = vendaDAO.getVendas();
    List<Compra> listaCompras = compraDAO.getCompras();

    for (Venda v : listaVendas) {
        String nomeCliente = v.getCliente().getNome();
        String ufCliente = v.getCliente().getUf();
        String nomeFornecedor = v.getFornecedor().getNome();
        String ufFornecedor = v.getFornecedor().getUf();
        String precoVendaStr = v.getPreco().replace(",", ".");

        double precoVenda = Double.parseDouble(precoVendaStr);
        double icms = ICMS.calcularICMS(precoVenda, 18); 

        String precoCompra = "N/A"; 

        for (Compra c : listaCompras) {
            if (
                c.getProduto().getId() == v.getProduto().getId() &&
                c.getCliente().getId() == v.getCliente().getId() &&
                c.getFornecedor().getId() == v.getFornecedor().getId()
            ) {
                precoCompra = c.getPreco();
                break;
            }
        }

        modelo.addRow(new Object[]{
            nomeCliente,
            ufCliente,
            nomeFornecedor,
            ufFornecedor,
            v.getPreco(),
            String.format("%.2f", icms),
            precoCompra,
            v.getPagamento()
        });
    }*/
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Relatorio;
    // End of variables declaration//GEN-END:variables
}
