/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ClienteDAO;
import DAO.FornecedorDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import beans.Cliente;
import beans.Fornecedor;
import beans.Produto;
//import beans.Venda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Venda extends javax.swing.JFrame {
    
    private Map<String, Fornecedor> FornecedorMap = new HashMap<>();
    private Map<String, Cliente> ClienteMap = new HashMap<>();
    private Map<String, Produto> ProdutoMap = new HashMap<>();

    /**
     * Creates new form CadastroProduto
     */
    public Venda() {
        initComponents();
        preencherComboFornecedor();
        preencherComboCliente();
        preencherCombProduto();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Preco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Venda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JblCadastro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Fornecedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmb_Cliente = new javax.swing.JComboBox<>();
        txt_EstadoFornecedor = new javax.swing.JTextField();
        txt_EstadoComprador = new javax.swing.JTextField();
        cmb_Produto = new javax.swing.JComboBox<>();
        cmb_Pagamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produto:");

        btn_Venda.setText("Confirmar Venda");
        btn_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VendaActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço:");

        JblCadastro.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        JblCadastro.setText("Venda");

        jLabel2.setText("Fornecedor:");

        cmb_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_FornecedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        txt_EstadoFornecedor.setEditable(false);
        txt_EstadoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EstadoFornecedorActionPerformed(evt);
            }
        });

        txt_EstadoComprador.setEditable(false);

        cmb_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ProdutoActionPerformed(evt);
            }
        });

        cmb_Pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Débito", "Crédito", " " }));

        jLabel5.setText("Pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmb_Cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Preco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Fornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Pagamento, 0, 170, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_EstadoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txt_EstadoComprador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(JblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btn_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(txt_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel1)))
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JblCadastro)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_EstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_EstadoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(cmb_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addComponent(btn_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VendaActionPerformed
    Venda v = new Venda();

    // Recupera os nomes selecionados nos JComboBox
    String nomeFornecedorSelecionado = (String) cmb_Fornecedor.getSelectedItem();
    String nomeClienteSelecionado = (String) cmb_Cliente.getSelectedItem();
    String nomeProdutoSelecionado = (String) cmb_Produto.getSelectedItem();
    String pagamentoSelecionado = (String) cmb_Pagamento.getSelectedItem();
    String preco = txt_Preco.getText(); // supondo que você tenha esse JTextField

    // Recupera os objetos correspondentes
    Fornecedor fornecedorSelecionado = FornecedorMap.get(nomeFornecedorSelecionado);
    Cliente clienteSelecionado = ClienteMap.get(nomeClienteSelecionado);
    Produto produtoSelecionado = ProdutoMap.get(nomeProdutoSelecionado);

    // Seta os valores no objeto Venda
    v.setFornecedor(fornecedorSelecionado);
    v.setCliente(clienteSelecionado);
    v.setProduto(produtoSelecionado);
    v.setPagamento(pagamentoSelecionado);
    v.setPreco(preco);

    // Insere a venda no banco
    VendaDAO vDAO = new VendaDAO();
    vDAO.inserir(v);

    // Mensagem de sucesso
    JOptionPane.showMessageDialog(this, "Registro efetuado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

    // Limpa o formulário
    limparFormulario();

    }//GEN-LAST:event_btn_VendaActionPerformed

    private void cmb_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ProdutoActionPerformed

    private void cmb_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_FornecedorActionPerformed

    private void txt_EstadoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EstadoFornecedorActionPerformed

    }//GEN-LAST:event_txt_EstadoFornecedorActionPerformed
    
    public void limparFormulario() {
        cmb_Fornecedor.setSelectedIndex(-1);
        cmb_Fornecedor.setSelectedIndex(-1);
    }
    
    public void preencherComboFornecedor() {
        FornecedorDAO fDAO = new FornecedorDAO();
        List<Fornecedor> listaFornecedores = fDAO.getFornecedores();

        for (Fornecedor fornecedor : listaFornecedores) {
            cmb_Fornecedor.addItem(fornecedor.getNome());
            FornecedorMap.put(fornecedor.getNome(), fornecedor);
        }

        cmb_Fornecedor.setSelectedIndex(-1);
 
    }

    public void preencherComboCliente() {
        ClienteDAO uDAO = new ClienteDAO();
        List<Cliente> listaClientes = uDAO.getCliente();

        for (Cliente cliente : listaClientes) {
            cmb_Cliente.addItem(cliente.getNome());
            ClienteMap.put(cliente.getNome(), cliente);
        }

        cmb_Cliente.setSelectedIndex(-1);
    }
    
     public void preencherCombProduto() {
        ProdutoDAO pDAO = new ProdutoDAO();
        List<Produto> listaProdutos = pDAO.getProdutos();

        for (Produto produto : listaProdutos) {
            cmb_Produto.addItem(produto.getNome());
            ProdutoMap.put(produto.getNome(), produto);
        }

        cmb_Produto.setSelectedIndex(-1);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblCadastro;
    private javax.swing.JButton btn_Venda;
    private javax.swing.JComboBox<String> cmb_Cliente;
    private javax.swing.JComboBox<String> cmb_Fornecedor;
    private javax.swing.JComboBox<String> cmb_Pagamento;
    private javax.swing.JComboBox<String> cmb_Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_EstadoComprador;
    private javax.swing.JTextField txt_EstadoFornecedor;
    private javax.swing.JTextField txt_Preco;
    // End of variables declaration//GEN-END:variables

    private void setFornecedor(Fornecedor fornecedorSelecionado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setCliente(Cliente clienteSelecionado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setProduto(Produto produtoSelecionado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setPagamento(String pagamentoSelecionado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setPreco(String preco) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    String getPreco() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
